### ISSUE TITLE
update `parser-attestor` usage

### ISSUE THREAD

**Issue by Autoparallel** [pluto/web-prover-circuits#22] opened 2024-11-01 00:43 UTC
# MIssion
Circuits and tests in `parser-attestor` have changed since the commit we brought in here. We should use the latest in `parser-attestor/main`

**Comment by 0xJepsen** [comment] 2024-11-01 01:55
Going to bang this out.

**Comment by lonerapier** [comment] 2024-11-01 03:26
I think this is duplicate of #19. We'll need to remove import of parser-attestor and use the newly brought in circuits directly

**Closed** 2024-11-01 19:05 UTC
